### ISSUE TITLE
tripfag finder can't remember window location

### ISSUE THREAD

**Issue by ImNotGivinMyNameToAMachine** [bstats/Tripfag-Finder#4]
tripfag finder can't remember window location. 

if you want the location to be "bottom of page, left side" every time then you have to change it every time. 

please fix this. 

also i'm using chromiumportable 31.0.1650.8 (226087), tampermonkey legacy 3.9.202, and tripfag-fidner 2.3.0 for tampermonkey, if that means anything. 
(also please dont' tell me to "'up'date". version 32 has drop-down menu's broken, after version 32 you can't copy-paste and retain extension data, etc..)

apparently the newer versions of tirpfag thread finder have had this issue since it stopped appearing in the bottom-left corner by default. 

i had the same problem in firefox 28. so i didn't update to fix it. it seems to be an isolated incident for tirpfag-finder. 

so i decided to namefag and post. also i remember hearing about this having some option to allow anonymous users to post. maybe turn that on, too. 

i hope you or someone who will fix this sees this and finally fixes this after all this time and i'm not wasting my time doing this. so. again. 

please fix this as fast as possible.

**Comment by bstats** [comment]
I can't test this because I can't install that version of chromium/tampermonkey. It works on latest chrome/ium. Update your shit.

**Comment by bstats** [comment]
Actually I just found the portable version of chromium v31 and I can't replicate your issue. It remembers the location fine.

**Comment by bstats** [comment]
> so i decided to namefag and post. also i remember hearing about this having some option to allow anonymous users to post. maybe turn that on, too.

That would be [NameSync](https://namesync.org/) you're thinking of

**Comment by specialeddy** [comment]
omg, chrome is up to version 51 now, you can't copy and paste what?

**Comment by ImNotGivinMyNameToAMachine** [comment]
> I can't test this because I can't install that version of chromium/tampermonkey. It works on latest chrome/ium. Update your shit.

you don't have to install it. use the portable version as a portable version. the new version is shit. update your shit. 

> Actually I just found the portable version of chromium v31 and I can't replicate your issue. It remembers the location fine.

well shit. maybe it has something to do with the fact that i'm always in private browsing. maybe separate that. if that's the case. - i probably should've mentioned that in retrospect. - also i could probably upload my exact copy of chromiumporable since it's portable - but i don't know what to upload to. i don't want dropbox because it's too machine-tied, name-tied, and use-identifiable. 

> That would be NameSync you're thinking of

no. i know that. i mean i decided to namefag here and post. but i remembering hearing that there's an option to have anonymous users post. if you could turn that on. 

> omg, chrome is up to version 51 now, you can't copy and paste what?

oyg, yes and, i can't copy paste the chromiumporable folder. - also since chromium the numbers have been severely inflated. if it were the firefox days then chromium would be up to version 5 now. and that would be considered a lot.

**Comment by bstats** [comment]
> maybe it has something to do with the fact that i'm always in private browsing.

Yeah, private browsing means no data is saved, so it is expected behavior for settings not to be saved.

This issue will remain closed
